version: 1.0.{build}

install:
  - cinst biicode mingw
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\ProgramData\chocolatey\lib\cmake.3.0.2\content\cmake-3.0.2-win32-x86\bin
  - cmd: set PATH=%PATH:Git\bin=%;C:\MinGW\bin
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii;  
  - cmd: cmake --version
  - cmd: g++ --version
  - cmd: bii --version

before_build:
  - cmd: bii init myproject
  - cmd: cd myproject
  - cmd: bii new diego/libcello
  # Yes, I know, sure this move can be improved
  - cmd: move ..\* blocks\diego\libcello\
  - cmd: move ..\demos blocks\diego\libcello\
  - cmd: move ..\include blocks\diego\libcello\
  - cmd: move ..\src blocks\diego\libcello\
  - cmd: move ..\editors blocks\diego\libcello\
  - cmd: move ..\tests blocks\diego\libcello\

build_script:
  - cmd: bii cpp:build

test_script:
  - cmd: bin\diego_libcello_tests_test.exe


